<?php

/*
+-----------------------------------------------------------------------+
| language/bg_BG/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Google контакт';
$labels['usegoogleabook'] = 'Използвай адресна книга от Google';
$labels['googleuser'] = 'Потребител';
$labels['googlepass'] = 'Парола';

?>