<?php

/*
+-----------------------------------------------------------------------+
| language/da_DK/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Google kontakter';
$labels['usegoogleabook'] = 'Brug Google adressebog';
$labels['googleuser'] = 'Google konto';
$labels['googlepass'] = 'Google password';
$labels['googlepassisset'] = 'Google password er indtastet';
$labels['googlepassisnotset'] = 'Google password er ikke indtastet';

$messages = array();
$messages['abookreadonly'] = 'Der kan ikke skrives i adressebogen.';

?>