<?php
$labels = array();
$labels['googlecontacts']  = 'Contactos de Google';
$labels['usegoogleabook']  = 'Usar o caderno de enderezos de Google';
$labels['googleuser'] = 'Conta de Google';
$labels['googlepass'] = 'Contrasinal de Google';
$labels['googlepassisset'] = 'O contrasinal de Google está configurado';
$labels['googlepassisnotset'] = 'O contrasinal de Google non está configurado';

$messages = array();
$messages['abookreadonly'] = 'O caderno de enderezos é de só lectura.';
?>