<?php
$labels = array();
$labels['googlecontacts']  = 'Contatti Google';
$labels['usegoogleabook']  = 'Usa rubrica Google';
$labels['googleuser'] = 'Conto su Google';
$labels['googlepass'] = 'Password di Google';
$labels['googlepassisset'] = 'La password di Google è già presente';
$labels['googlepassisnotset'] = 'La password di Google non è presente';

$messages = array();
$messages['abookreadonly'] = 'La rubrica è in sola lettura.';
?>