<?php

/*
+-----------------------------------------------------------------------+
| language/nl_NL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Google Contacten';
$labels['usegoogleabook'] = 'Gebruik Google adresboek';
$labels['googleuser'] = 'Google Account';
$labels['googlepass'] = 'Google Wachtwoord';
$labels['googlepassisset'] = 'Google Wachtwoord is ingesteld';
$labels['googlepassisnotset'] = 'Google Wachtwoord is niet ingesteld';

?>