<?php

/*
+-----------------------------------------------------------------------+
| language/pt_BR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: trturino                                                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['googlecontacts'] = 'Contatos Google';
$labels['usegoogleabook'] = 'Usar catálogo de endereços do Google';
$labels['googleuser'] = 'Conta Google';
$labels['googlepass'] = 'Senha Google';
$labels['googlepassisset'] = 'Senha está preenchida';
$labels['googlepassisnotset'] = 'Senha não está preenchida';

?>