<?php
$labels = array();
$labels['googlecontacts']  = 'Google Kontakter';
$labels['usegoogleabook']  = 'Använd Googles adressbok';
$labels['googleuser'] = 'Google-konto';
$labels['googlepass'] = 'Google-lösenord';
$labels['googlepassisset'] = 'Google-lösenord är inställt';
$labels['googlepassisnotset'] = 'Google-lösenord är inte inställt';

$messages = array();
$messages['abookreadonly'] = 'Adressboken går endast att läsa.';
?>
